name:                maki
version:             0.1.0.0
github:              "mattmoore/maki"
license:             MIT
author:              "Matt Moore"
maintainer:          "matt@mattmoore.io"
copyright:           "2020 Matt Moore"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Meta-Advanced Kotlin Implementation - An alternative Kotlin compiler and runtime with advanced metaprogramming capabilities.
# category:            Compiler

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mattmoore/maki#readme>

dependencies:
- base >= 4.7 && < 5
- parsec

library:
  source-dirs: src

executables:
  maki-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maki

tests:
  maki-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maki
